name: Build and test
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php: ["7.2", "7.3", "7.4", "8.0", "8.1.0"]
        env: ["^3", "^4", "^5", "^6"]
        exclude:
          - php: "7.2"
            env: "^6"
          - php: "7.3"
            env: "^6"
          - php: "7.4"
            env: "^6"
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Require dependencies
        run: COMPOSER_MEMORY_LIMIT=-1 composer require symfony/console:${{matrix.env}} symfony/framework-bundle:${{matrix.env}} symfony/http-kernel:${{matrix.env}} --prefer-source

      - name: Install dependencies
        run: COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-source

      - name: run tests
        run: XDEBUG_MODE=coverage ./bin/phpunit --coverage-text
